### ISSUE TITLE
'OR' mode for notifications API

### ISSUE THREAD

**Issue by phindmarsh** [carnivalmobile/carnival-platform#1]
We have a use case where we want to send a notification to a bunch of users while avoiding sending duplicates. The users are matched using tags or a series of attributes using the `v3` notifications API.

Currently all the objects in the `to` array are combined with an `AND` which means we need to make several requests, one for the tags and one for each attribute. Since users can subscribe to multiple attributes or tags we risk sending the same notification to the same person several times. We can solve this by including everything in each request with a `not_filter` on each except one. This kinda works, except where people subscribe to two different attributes, they would both be excluded based on the `not_filter` and the user would not receive a notification at all.

If we had the ability to say "send to users where they match _any_ of the criteria in the `to` field" it would mean we could send a single request, have Carnival match users that have any of the tags/attributes and avoid any of the risks of duplicates or not sending any at all. 

Perhaps adding a syntax like:

``` json
{
  "notification": {
    "to": [],
    "match_to_using": "or",
    "payload": {}
}
```

Where `match_to_string` is either `and` (the default) or `or`.

Hope that makes sense!

**Comment by samjarman** [comment]
Hi Patrick, 

Sounds like an interesting suggestion, will discuss with the team!

Sam

**Comment by splant** [comment]
Moving into private repo for issue tracking
