### ISSUE TITLE
web-api errors out when s3_file_name is present for unsupported message type

### ISSUE THREAD

**Issue by nobbyclark** [carnivalmobile/carnival-platform#3]
When creating a new message on the front-end with a video and then switching to another message type that does not support video, the web-api throws an error and breaks the front-end UI.

```
Problem: Attempted to set a value for 's3_file_name' which is not allowed on the model Messages::ImageMessage. Summary: Without including Mongoid::Attributes::Dynamic in your model and the attribute does not already exist in the attributes hash, attempting to call Messages::ImageMessage#s3_file_name= for it is not allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and is raised instead of getting a NoMethodError. Resolution: You can include Mongoid::Attributes::Dynamic if you expect to be writing values for undefined fields often.
```

Steps to re-create:

1. Select a video message
2. Upload a video
3. Switch to a different message type e.g. Image message
4. Select "Preview"

Possible Fixes:

* Clear `s3_file_name` attribute before persisting to the web-api

**Comment by splant** [comment]
This issue was moved to carnivalmobile/platform#59
